"""add access status to purchases

Revision ID: 079739c0e294
Revises: 7d7ffbcbe075
Create Date: 2026-07-10 16:37:32.624912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079739c0e294'
down_revision = '7d7ffbcbe075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('access_status')

    # ### end Alembic commands ###
