"""add checkout session id to purchases

Revision ID: 7d7ffbcbe075
Revises: dd5a44cdd1ea
Create Date: 2026-07-09 16:32:51.909351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d7ffbcbe075'
down_revision = 'dd5a44cdd1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_session_id', sa.String(length=255), nullable=False))
        batch_op.drop_constraint(batch_op.f('purchases_stripe_checkout_session_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['checkout_session_id'])
        batch_op.drop_column('github_invitation_id')
        batch_op.drop_column('stripe_payment_intent_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('stripe_checkout_session_id')
        batch_op.drop_column('github_access_granted')
        batch_op.drop_column('purchased_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('github_access_granted', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('stripe_checkout_session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('github_invitation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('purchases_stripe_checkout_session_id_key'), ['stripe_checkout_session_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('checkout_session_id')

    # ### end Alembic commands ###
